development:
  adapter: postgresql
  database: project_bus_development
  reconnect: false
  pool: 10
  min_messages: WARNING

test:
  adapter: postgresql
  database: project_bus_development_test
  reconnect: false
  pool: 10
  min_messages: WARNING
